backend:
  name: git-gateway
  branch: main
  repo: tonPseudoGithub/carla-portfolio

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Galeries"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Photos",
          name: "photos",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }

  - name: "about"
    label: "Page À propos"
    files:               # ✅ <<-- ici : files (et pas file)
      - file: "src/content/about.md"
        label: "Page À propos"
        name: "about"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Texte", name: "body", widget: "markdown" }

  - name: "tarifs"
    label: "Tarifs"
    folder: "src/content/tarifs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom du forfait", name: "title", widget: "string" }
      - { label: "Prix", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
